# Generated by Django 5.2.17 on 2026-08-13 14:14

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[A-Z0-9-]{3,32}$"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cpu", "cpu"),
                            ("motherboard", "motherboard"),
                            ("memory", "memory"),
                            ("storage", "storage"),
                            ("psu", "psu"),
                            ("case", "case"),
                            ("gpu", "gpu"),
                            ("cpu_cooler", "cpu_cooler"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField()),
                ("is_listed", models.BooleanField(default=True)),
                ("socket", models.CharField(blank=True, default="", max_length=32)),
                ("tdp_watts", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "memory_type",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "form_factor",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "memory_slot_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("sata_port_count", models.PositiveIntegerField(blank=True, null=True)),
                ("m2_slot_count", models.PositiveIntegerField(blank=True, null=True)),
                ("module_count", models.PositiveIntegerField(blank=True, null=True)),
                ("capacity_gb", models.PositiveIntegerField(blank=True, null=True)),
                ("length_mm", models.PositiveIntegerField(blank=True, null=True)),
                ("interface", models.CharField(blank=True, default="", max_length=8)),
                ("wattage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "max_gpu_length_mm",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_cooler_height_mm",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("height_mm", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "paid"),
                            ("preparing", "preparing"),
                            ("shipped", "shipped"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=64)),
                (
                    "postal_code",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(regex="^[0-9]{7}$")
                        ],
                    ),
                ),
                ("prefecture", models.CharField(max_length=8)),
                ("city", models.CharField(max_length=64)),
                ("address_line", models.CharField(max_length=128)),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[0-9]{10,11}$"
                            )
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cpu", "cpu"),
                            ("motherboard", "motherboard"),
                            ("memory", "memory"),
                            ("storage", "storage"),
                            ("psu", "psu"),
                            ("case", "case"),
                            ("gpu", "gpu"),
                            ("cpu_cooler", "cpu_cooler"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sku", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="application.order",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="application.part",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "category"),
                        name="order_line_unique_category_per_order",
                    )
                ],
            },
        ),
    ]
