# Generated by Django 5.2.17 on 2026-08-13 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 1)),
                name="order_total_price_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["paid", "preparing", "shipped", "cancelled"])
                ),
                name="order_status_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 1)), name="order_line_quantity_is_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 1)),
                name="order_line_unit_price_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 1)), name="part_unit_price_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        [
                            "cpu",
                            "motherboard",
                            "memory",
                            "storage",
                            "psu",
                            "case",
                            "gpu",
                            "cpu_cooler",
                        ],
                    )
                ),
                name="part_category_allowed",
            ),
        ),
    ]
